# Docker Compose for Behold WhatsApp Integration
# Includes the main app, optional Redis for caching, and PostgreSQL for sessions

version: '3.8'

services:
  # Main WhatsApp application
  whatsapp-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      # WhatsApp Configuration
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WHATSAPP_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN}
      
      # Shopify Configuration
      - SHOPIFY_STORE=${SHOPIFY_STORE}
      - SHOPIFY_ADMIN_TOKEN=${SHOPIFY_ADMIN_TOKEN}
      - SHOPIFY_STOREFRONT_TOKEN=${SHOPIFY_STOREFRONT_TOKEN}
      - SHOPIFY_API_VERSION=${SHOPIFY_API_VERSION:-2025-07}
      
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Optional: Database URL (uncomment if using PostgreSQL)
      # - DATABASE_URL=postgresql://postgres:password@postgres:5432/whatsapp_sessions
      
      # Optional: Redis URL (uncomment if using Redis)
      # - REDIS_URL=redis://redis:6379/0
      
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
      # - postgres  # Uncomment if using PostgreSQL
    restart: unless-stopped
    networks:
      - whatsapp-network

  # Redis for session caching (optional but recommended)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - whatsapp-network
    command: redis-server --appendonly yes

  # PostgreSQL for session storage (optional, uncomment if needed)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_DB=whatsapp_sessions
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - whatsapp-network

  # Nginx reverse proxy (optional, for production)
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/ssl/certs
  #   depends_on:
  #     - whatsapp-bot
  #   restart: unless-stopped
  #   networks:
  #     - whatsapp-network

volumes:
  redis_data:
  # postgres_data:  # Uncomment if using PostgreSQL

networks:
  whatsapp-network:
    driver: bridge

